service: ishawkercentreclosed

frameworkVersion: '2'

custom:
  bot: src/bot
  reader: src/reader
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: 'arn:aws:dynamodb:ap-southeast-1:*:table/ishawkercentreclosed'
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: 'arn:aws:dynamodb:ap-southeast-1:*:table/ihcc-hawkerCentres'
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: 'arn:aws:dynamodb:ap-southeast-1:*:table/ihcc-users'

package:
  patterns:
    - '!./**'
    - 'src/**'

functions:
  search:
    handler: ${self:custom.reader}/handler.search
    events:
      - http:
          method: get
          path: /search
  bot:
    handler: ${self:custom.bot}/handler.bot
    events:
      - http:
          method: post
          path: /bot
