service: ishawkercentreclosed

frameworkVersion: '2'

custom:
  bot: src/bot
  table:
    results: ihcc-results
    hc: ihcc-hawkerCentres
    users: ihcc-users
    feedback: ihcc-feedback
  webpack:
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  lambdaHashingVersion: 20201221
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TABLE_RESULTS: ${self:custom.table.results}-${self:provider.stage}
    TABLE_HC: ${self:custom.table.hc}-${self:provider.stage}
    TABLE_USERS: ${self:custom.table.users}-${self:provider.stage}
    TABLE_FEEDBACK: ${self:custom.table.feedback}-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table.results}-${self:provider.stage}'
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table.hc}-${self:provider.stage}'
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table.users}-${self:provider.stage}'
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.table.feedback}-${self:provider.stage}'

package:
  patterns:
    - '!./**'
    - 'src/**'

functions:
  bot:
    handler: ${self:custom.bot}/handler.bot
    events:
      - http:
          method: post
          path: /bot
