service: ishawkercentreclosed

frameworkVersion: '2'

custom:
  dotenv:
    exclude:
      - APIG_DEV
      - APIG_PROD
    required:
      env:
        - BOT_TOKEN
        - REGION
        - TABLE_NAME_RESULTS
        - TABLE_NAME_HC
        - TABLE_NAME_USERS
        - TABLE_NAME_FEEDBACK
  webpack:
    includeModules: true
  botFolder: src/bot

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  lambdaHashingVersion: 20201221
  environment:
    TZ: Asia/Singapore
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    BOT_TOKEN: ${env:BOT_TOKEN}
    TABLE_RESULTS: ${env:TABLE_NAME_RESULTS}-${self:provider.stage}
    TABLE_HC: ${env:TABLE_NAME_HC}-${self:provider.stage}
    TABLE_USERS: ${env:TABLE_NAME_USERS}-${self:provider.stage}
    TABLE_FEEDBACK: ${env:TABLE_NAME_FEEDBACK}-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${env:TABLE_NAME_RESULTS}-${self:provider.stage}'
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${env:TABLE_NAME_HC}-${self:provider.stage}'
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${env:TABLE_NAME_USERS}-${self:provider.stage}'
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${env:TABLE_NAME_FEEDBACK}-${self:provider.stage}'

package:
  patterns:
    - '!./**'
    - 'src/**'

functions:
  bot:
    handler: ${self:custom.botFolder}/handler.bot
    events:
      - http:
          method: post
          path: /bot
  notifications:
    handler: ${self:custom.botFolder}/handler.notifications
    events:
      - http:
          method: get
          path: /notifications
