const hcKeywords: Record<string, string[]> = {
  'Adam Road Food Centre': ['botanic'],
  'Ang Mo Kio Ave 6 Blk 724': ['ang mo kio central'],
  'Ang Mo Kio Ave 10 Blk 527': ['chengsan'],
  'Aljunied Ave 2 Blk 117': ['geylang east'],
  'Bedok Food Centre': ['kew'],
  'Bedok North Street 1 Blk 216': ['heartbeat'],
  'Bedok North Street 4 Blk 85': ['feng shan'],
  'Berseh Food Centre': ['besar', 'jalan besar'],
  'Buffalo Road Blk 665': ['little india'],
  'Bukit Merah Central Blk 163': ['henderson'],
  'Bukit Panjang Hawker Centre and Market': ['bangkit'],
  'Bukit Timah Market': ['beauty world'],
  'Ci Yuan Hawker Centre': ['ciyuan'],
  'Circuit Road Blk 80': ['mattar'],
  'Circuit Road Blk 89': ['mattar'],
  'East Coast Lagoon Food Village': ['east coast', 'east coast park'],
  'Fernvale Hawker Centre and Market': [
    'sengkang',
    'seng kang',
    'sengkang west',
  ],
  'Geylang Bahru Blk 69': ['kallang bahru'],
  'Ghim Moh Road Blk 20': ['buona vista'],
  'Golden Mile Food Centre': ['beach'],
  'New Market Road Blk 32': ['people park'],
  'Jurong East Ave 1 Blk 347': ['yu hua'],
  'Jurong East Street 24 Blk 254': ['yu hua'],
  'Jurong West Street 52 Blk 505': ['hongkah', 'hong kah'],
  'Hougang Ave 1 Blk 105': ['lorong ah soo'],
  'Mei Chin Road Blk 159': ['mei ling', 'meiling', 'stirling'],
  'New Upper Changi Road Blk 58': ['bedok south'],
  'Old Airport Road Blk 51': ['kallang airport'],
  'Queen Street Blk 270': ['waterloo'],
  'Redhill Lane Blk 79': ['red hill'],
  'Redhill Lane Blk 85': ['red hill'],
  'Sembawang Hills Food Centre': ['upper thomson'],
  'Taman Jurong Market and Food Centre': ['yuan ching'],
};

export default hcKeywords;
